### ISSUE TITLE
Model Crashes

### ISSUE THREAD

**Issue by msemrtes** [Joschuka/Project-G1M#6]
Every Time I Opened A Model, It Crashes For No Reason. Can You Fix It?

**Comment by Joschuka** [comment]
I need more information than that.

**Comment by msemrtes** [comment]
> I need more information than that.

Well The Models Om Trying To Open Is The Persona 5 Strikers Models. They Are In G1M Format. The Textures(G1T) Are Stored Sepretly. This Could Be The Reason, Can It? Or Maeby More Files And Animations(G1A) Need To Merge?

**Comment by Joschuka** [comment]
P5S works fine with the plugin, several people were able to open the assets, you shouldn't have any crash. Your assets are most likely corrupted.
g1t and g1a being separated from the g1m doesn't lead to a crash. Make sure not to have the "merge all" option selected when opening a g1m since they're all in the same place, this is the only reason I can think of that would lead to a crash on a computer with limited resources.

**Comment by msemrtes** [comment]
Not Merging All Animations Does Not Fix Many Models. Maybe It Is Corrupted
Since The Models Had To Be Renamed.

**Comment by Joschuka** [comment]
Sorry I don't understand the issue and can't help you, P5S works for many users so it's probably a problem with the extraction of the game, which is not relevant to this repository.
Make sure that you have a valid game dump, if you have the PC version files are encrypted and must be using the corresponding command https://forum.xentax.com/viewtopic.php?f=10&t=21679&start=255#p171805 , this is the only thing I can think of.
