### ISSUE TITLE
Newest version of Project-G1M doesn't work with FEW bone models

### ISSUE THREAD

**Issue by Andree12** [Joschuka/Project-G1M#8]
[FEW model.zip](https://github.com/Joschuka/Project-G1M/files/7010966/FEW.model.zip)
The files like 0000.g1m doesn't work with the newest version of Project-G1M, can you please fix it?

**Comment by Joschuka** [comment]
Yeah you're opening it alone right ? 
I decided not to load skeleton only g1m files alone, if you use the "merge all " option it'll load everything fine, it's been like this since the beginning of the C++ plugin.
I can add skeleton only g1m loading if you really want it though, I'll do that tomorrow.

**Comment by Andree12** [comment]
> I can add skeleton only g1m loading if you really want it though, I'll do that tomorrow.

Yeah, you can add that.

**Comment by Joschuka** [comment]
> But, I tried the "merge all" option and then it gave me a error but that turns out that I was using a older version of Noesis so I updated it.

Ah yes this is probably because of the new joint color feature that was added in the recent Noesis versions. I should add a version check to warn users if their version is too old. One thing you can do to make sure you always have the latest version is too go to the data viewer then under "persistent settings" -> "System" set the "Check for updates on startup" to 1.

Anyways I just added the skeleton only g1m display, I'll let you test and close the issue if it's solved as usual, thanks for the report.

**Comment by Andree12** [comment]
> Anyways I just added the skeleton only g1m display, I'll let you test and close the issue if it's solved as usual, thanks for the report.

Ok, it works. Thanks!
